# Generated by Django 3.2.4 on 2022-04-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address'),
        ),
    ]
